# Generated by Django 4.2 on 2023-04-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default='3'),
        ),
    ]
